# Generated by Django 4.2 on 2023-04-05 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dateEntry',
            field=models.DateField(default=datetime.date.today, verbose_name='DD.MM:YYYY'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='releaseDate',
            field=models.DateField(default=datetime.date.today, verbose_name='DD.MM:YYYY'),
        ),
    ]
