# Generated by Django 4.2 on 2023-04-05 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_dateentry_alter_staff_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dateEntry',
            field=models.DateField(default=datetime.date.today, verbose_name='Giriş Tarihi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='releaseDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Çıkış Tarihi'),
        ),
    ]
