# Generated by Django 4.2 on 2023-04-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_dateentry_alter_staff_releasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customerMail',
            field=models.EmailField(default='', max_length=200, verbose_name='Müşteri E-postası'),
        ),
        migrations.AddField(
            model_name='project',
            name='customerName',
            field=models.CharField(default='', max_length=200, verbose_name='Müşteri İsmi'),
        ),
        migrations.AddField(
            model_name='project',
            name='customerPhone',
            field=models.CharField(default='', max_length=200, verbose_name='Müşteri Telefon Numarası'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectAdress',
            field=models.TextField(default='', verbose_name='Proje Adresi'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectManager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='staff.staff', verbose_name='Proje Yöneticisi'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectName',
            field=models.CharField(default='', max_length=200, verbose_name='Proje Adı'),
        ),
    ]
