# Generated by Django 4.2 on 2023-04-06 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_projectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dateofBirth',
            field=models.DateField(default=datetime.date.today, verbose_name='Doğum Tarihi'),
        ),
    ]
