# Generated by Django 4.2 on 2023-04-06 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staff_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='adress',
            field=models.TextField(blank=True, default='', verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('0', '0 Rh(-)'), ('00', '0 Rh(+)'), ('A', 'A Rh(-)'), ('AA', 'A Rh(+)'), ('B', 'B Rh(-)'), ('BB', 'B Rh(+)'), ('AB', 'AB Rh(-'), ('AABB', 'AB Rh(+)')], default='', max_length=10, verbose_name='Kan Grubu'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='county',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dateEntry',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Giriş Tarihi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dateofBirth',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='district',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, verbose_name='E-Posta'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergencyPhoneNumber',
            field=models.CharField(blank=True, default='', max_length=21, verbose_name='Acil Durumda Aranacak Kişi Tel'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phoneNumber',
            field=models.CharField(blank=True, default='', max_length=21, verbose_name='Cep Tel'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='projectName',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='staff.project', verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='releaseDate',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Çıkış Tarihi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Ünvan'),
        ),
    ]
