# Generated by Django 4.2 on 2023-04-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_staff_adress_alter_staff_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='idNumber',
            field=models.PositiveIntegerField(default=False, max_length=15, verbose_name='TC Kimlik No'),
        ),
    ]
