# Generated by Django 4.2 on 2023-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_projectname'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='participants',
        ),
        migrations.AddField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(default=1, to='staff.staff', verbose_name='Katılımcılar'),
        ),
    ]
