# Generated by Django 4.2 on 2023-04-06 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_projectname'),
        ('training', '0002_remove_training_participants_training_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='projectName',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.SET_DEFAULT, to='staff.project', verbose_name='Proje'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainingTime',
            field=models.CharField(default='', max_length=200, verbose_name='Eğitim Süresi'),
        ),
    ]
