# Generated by Django 4.2 on 2023-04-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_training_projectname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Açıklama'),
        ),
    ]
