# Generated by Django 4.2 on 2023-04-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_staff_idnumber'),
        ('training', '0006_alter_training_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(default=[0], to='staff.staff', verbose_name='Katılımcılar'),
        ),
    ]
